export const WAIT_DEVICE = 'WAIT_DEVICE';
export const IS_MOBILE_DEVICE = 'IS_MOBILE_DEVICE';
export const IS_GAME_START = 'IS_GAME_START';
export const AIRPLANE_MOVING = 'AIRPLANE_MOVING';
export const OBSTACLE_MOVING = 'OBSTACLE_MOVING';
export const IS_GAME_OVER = 'IS_GAME_OVER';
